version: '2'
services:
  ms05-app:
    image: ms05
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://ms05-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=ms05
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  ms05-mongodb:
    extends:
      file: mongodb.yml
      service: ms05-mongodb
